name: Playwright-allure-report

on:
  push:
    branches:
      - allureReportsAndGitHubPages
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          # renovate: node-version
          node-version: '18.19.1'

      - name: Install Playwright Deps
        run: npx playwright install-deps chromium

      - name: Install Libraries
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
        
      - name: Allure Report Action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy Report to Git hub pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

