#Playwright Allure report with GitHub Pages
name: Playwright-allure-report

on:
  # push:
  #   branches:
  #     - allureReportsAndGitHubPages
  # pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright Deps
        run: npx playwright install-deps chromium

      - name: Install Libraries
        run: npm ci --verbose

      - name: Run tests
        run: npm test --verbose
        continue-on-error: true
    
      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
  
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        continue-on-error: true
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results

      # - name: Generate Allure Report
      #   run: |
      #     npm run allure:generate
      #     npm run allure:open

      # - name: Move Allure History to gh-pages
      #   if: always()
      #   run: |
      #     mkdir -p gh-pages/last-history
      #     cp -r allure-results/history/. gh-pages/last-history
  
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
